### ISSUE TITLE
LGPL licence

### ISSUE THREAD

**Issue by aDevilInMe** [HyEvil/oolua_support_overload#1]
Although not stated in the gist [1], this code is MIT. Would you kindly remove the LGPL which you have added.

Thanks.

[1] https://gist.github.com/aDevilInMe/2419c35c615b2319138b

**Comment by HyEvil** [comment]
I'm Sorry。The Licence has changed~~~    ^_^

**Comment by aDevilInMe** [comment]
Thank you for correcting this.
